relativeURLs = true
title = "Harpreet Singh"
theme = "academimal"
sectionPagesMenu = "main"
defaultContentLanguage = "en"
ignorefiles = [ "hugo_travis_ci", ".travis.yml" ]

[params]
    shortbio = "Sr. Research Associate, J-PAL South Asia"
    logo = "Singh_headshot.jpg" 
    
